name: Docker Image CI for GHCR

on: 
  push:
  workflow_run:
    workflows: ["Update the demo"]
    types:
      - completed

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write    
    steps:
      - uses: actions/checkout@v3
      - name: build and push the image
        run: |
          docker login --username manatlan --password ${{secrets.GITHUB_TOKEN}} ghcr.io
          docker build . --tag ghcr.io/manatlan/htagdemo:latest
          docker push ghcr.io/manatlan/htagdemo:latest

      - name: Call secure URL (render.com redeploy)
        env:
          MY_SECURE_URL: ${{ secrets.SECRET_URL }}
        run: |
          curl -X GET "$MY_SECURE_URL"