name: Update the demo

on:
  workflow_dispatch:
#  schedule:
    # every day at 3:00 AM
    # - cron:  '0 3 * * *'
# push:
#   branches:
#     - master
      
jobs:
  
  tests:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "install wget"
        run: |
          sudo apt-get -y install wget

      - name: "update repo"
        run: |
          cd app_demo
          rm -rf DEMOS app.py
          wget https://www.mlan.fr/api/DEMO_download
          unzip -o DEMO_download
          mv DEMO.py app.py
          rm DEMO_download        
          
      - name: Commit the new demo sources
        uses: EndBug/add-and-commit@v9
        with:
          message: 'update DEMO'
          add: 'app_demo/*'
